import type { Metadata } from "next";
import { Crimson_Text } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";

const crimsonText = Crimson_Text({
  weight: "400",
  variable: "--font-crimson-text",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${crimsonText.variable} antialiased text-2xl`}>
        <div className="bg-white dark:bg-black min-h-screen text-slate-700 dark:text-slate-100 overflow-hidden">
          <Navbar />
          <div className="py-12">{children}</div>
        </div>
      </body>
    </html>
  );
}
